- name: copy runfile to host
  copy:
    src: "../files/{{ runfile }}"
    dest: "/opt/{{ runfile }}"

- name: remove nouveau module
  shell: rmmod nouveau
  ignore_errors: true

- name: install epel-release
  yum:
    name: epel-release
    state: present


- name: install dkms 
  yum:
    name: dkms
    state: present

- name: install runfile 
  shell: sh {{ runfile }} -s --dkms
  args:
    chdir: /opt 
    creates: /usr/bin/nvidia-smi
  notify:
    - enable persist
