- hosts: all
  gather_facts: false
  tasks:
  - name: stop & disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no
  - name: copy weed binary
    copy:
      src: "files/weed"
      dest: /usr/local/bin/weed
      mode: '0755'
  - name: mkdir work dir
    file:
      path: /opt/weed
      state: directory

- hosts: weedmasters
  gather_facts: false
  tasks:
  - name: mkdir weedmaster dir
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ weedmasterdir1 }}"
      - "{{ weedmasterdir2 }}"
    
  - name: generate weedmaster service
    template:
      src: "templates/{{item}}.service.j2"
      dest: "/etc/systemd/system/{{item}}.service"
    with_items:
      - weedmaster1
      - weedmaster2
    notify:
      - start weedmaster

  handlers:
    - name: start weedmaster
      systemd:
        daemon-reload: yes
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - weedmaster1
        - weedmaster2

- hosts: weedvolumes
  gather_facts: false
  tasks:
  - name: mkdir weedvolume dir
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ weedvolumedir1 }}"
      - "{{ weedvolumedir2 }}"

  
  - name: generate weedvolume service
    template:
      src: "templates/{{item}}.service.j2"
      dest: "/etc/systemd/system/{{item}}.service"
    with_items:
      - weedvolume1
      - weedvolume2
    notify:
      - start weedvolume

  handlers:
    - name: start weedvolume
      systemd:
        daemon-reload: yes
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - weedvolume1
        - weedvolume2

- hosts: weedfilers
  gather_facts: false
  tasks:
  - name: generate weedfiler service
    template:
      src: templates/weedfiler.service.j2
      dest: /etc/systemd/system/weedfiler.service
    notify:
      - start weedfiler


  handlers:
    - name: start weedfiler 
      systemd:
        daemon-reload: yes
        name: weedfiler
        state: started
        enabled: yes
