- name: copy cfssl 
  copy:
    src: ../files/{{ item }}
    dest: /usr/local/bin/{{ item }}
    mode: '0755'
  with_items:
    - cfssl
    - cfssl-certinfo
    - cfssljson

- name: mkdir output
  file:
    path: roles/cert/output
    state: directory

- name: generate ca 
  shell: cfssl gencert -initca ca-csr.json | cfssljson -bare ca 
  args:
    chdir: roles/cert/output/

- name: import kubectl vars
  include_vars:
    dir: ../../kubectl/vars/
- include_tasks: roles/cert/tasks/certcommon.yml

- name: import etcd vars
  include_vars:
    dir: ../../etcd/vars/
- include_tasks: roles/cert/tasks/certcommon.yml

- name: import kubernetes vars
  include_vars:
    dir: ../../kube-apiserver/vars/
- include_tasks: roles/cert/tasks/certcommon.yml

- name: import proxy-client vars
  include_vars:
    dir: ../../metrics-server/vars/
- include_tasks: roles/cert/tasks/certcommon.yml

- name: import kube-controller-manager vars
  include_vars:
    dir: ../../kube-controller-manager/vars/
- include_tasks: roles/cert/tasks/certcommon.yml

- name: import kube-scheduler vars
  include_vars:
    dir: ../../kube-scheduler/vars/
- include_tasks: roles/cert/tasks/certcommon.yml

- name: import flanneld vars
  include_vars:
    dir: ../../flanneld/vars/
- include_tasks: roles/cert/tasks/certcommon.yml

- name: import kube-proxy vars
  include_vars:
    dir: ../../kube-proxy/vars/
- include_tasks: roles/cert/tasks/certcommon.yml
