apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-repo-pvc
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: registry
    spec:
      volumes:
        - name: repo-vol
          persistentVolumeClaim:
            claimName: docker-repo-pvc
      containers:
        - name: registry
          image: registry
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: repo-vol
              mountPath: /var/lib/registry
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  selector:
    app: registry
  ports:
  - port: 1180
    targetPort: 5000
