- name: mkdir work dir
  file:
    path: /opt/weed
    state: directory

- name: mkdir weedmaster dir
  file:
    path: "{{ weedmasterdir }}"
    state: directory
  delegate_to: "{{ item }}"
  with_items: 
    - "{{ groups['weedmasters'] }}" 

- name: mkdir weedvolume dir
  file:
    path: "{{ weedvolumedir }}"
    state: directory
  delegate_to: "{{ item }}"
  with_items: 
    - "{{ groups['weedvolumes'] }}" 

- name: copy weed binary
  copy:
    src: "files/{{ ansible_role_name }}/weed"
    dest: /usr/local/bin/weed
    mode: '0755'

- name: generate weedmaster service
  template:
    src: templates/weedmaster.service.j2
    dest: /etc/systemd/system/weedmaster.service 
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups['weedmasters'] }}"
  notify:
    - start weedmaster

- meta: flush_handlers

- name: generate weedvolume service
  template:
    src: templates/weedvolume.service.j2
    dest: /etc/systemd/system/weedvolume.service 
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups['weedvolumes'] }}"
  notify:
    - start weedvolume

- meta: flush_handlers

- name: generate weedfiler service
  template:
    src: templates/weedfiler.service.j2
    dest: /etc/systemd/system/weedfiler.service 
  delegate_to: "{{ item }}"
  run_once: true
  with_items:
    - "{{ groups['weedfilers'] }}"
  notify:
    - start weedfiler

