- name: copy helm to first master host
  copy: 
    src: ../files/helm
    dest: /usr/local/bin/helm
    mode: '0755'
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"
 
- name: copy nfs helm package
  copy: 
    src: ../files/nfs-subdir-external-provisioner-4.0.12.tgz
    dest: /opt/nfs-subdir-external-provisioner-4.0.12.tgz
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"
   
- name: install nfs-utils on all workers
  yum:
    name: nfs-utils
    state: present
  delegate_to: "{{ item }}"
  with_items: "{{ groups['workers'] }}"  

- name: check if nfs-client sc exists
  shell: kubectl get pods|grep nfssc-nfs-subdir-external-provisioner 
  ignore_errors: true
  register: storageclass
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: deploy nfs storageclass
  shell: helm install nfssc /opt/nfs-subdir-external-provisioner-4.0.12.tgz --set nfs.server={{ nfsserver }} --set nfs.path={{ nfspath }}
  when: " '1/1' not in storageclass.stdout "
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"
