rolename: kube-apiserver
node_port_range: 30000-32767
servicename: kube-apiserver
hosts_list:  '{% for item in groups["masters"] %}
"{{ hostvars[item].ansible_ssh_host }}",
{% endfor %} "127.0.0.1","{{ service_cidr_prefix }}1","kubernetes",
    "kubernetes.default",
    "kubernetes.default.svc",
    "kubernetes.default.svc.cluster",
    "kubernetes.default.svc.cluster.local."'
cn: kubernetes-master
orga: k8s
etcd_endpoints: '{% for item in groups["etcd"] %}
{%- if not loop.last -%}
https://{{ hostvars[item].ansible_ssh_host }}:2379,
{%- else -%}
https://{{ hostvars[item].ansible_ssh_host }}:2379
{%- endif -%}
{% endfor %}'
