- name: copy nvidia-docker repo
  copy: 
    src: ../files/nvidia-docker.repo
    dest: /etc/yum.repos.d/nvidia-docker.repo

- name: install nvidia-docker2
  yum:
    update_cache: yes
    name: nvidia-docker2
    state: present
  

- name: copy daemon.json
  copy:
    src: ../files/daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - restart docker
