- name: copy kubectl 
  copy: 
    src: ../files/kubectl
    dest: /usr/bin/kubectl
    mode: '0755'
- name: mkdir for k8s
  file:
    path: /root/.kube
    state: directory
- name: copy kubectl cert
  copy: 
    src: ../../cert/output/{{ item  }}
    dest: /opt/k8s/cert/{{ item }}
  with_items:
    - "{{ rolename }}.pem"
    - "{{ rolename }}-key.pem"
    - ca.pem
  
- name: genecert kubeconfig
  include_tasks: roles/master/tasks/kubeconfig.yml
- name: mv kubectl kubeconfig to config
  command: cp /opt/k8s/cfg/"{{ rolename }}.kubeconfig" /root/.kube/config
  args:
    creates: /root/.kube/config
