- include_tasks: setuphttpserver.yml

- name: create etcd directories
  file:
    path: "{{ etcd.etcd_workingdir }}/{{ item }}"
    state: directory
  with_items:
    - bin
    - cert
    - data
    - wal
- name: copy etcdctl bin
  get_url:
    url: "{{ httpurl }}/{{ ansible_role_name }}/{{ item }}"
  #copy:
  #  src: roles/etcd/files/{{ item }}
    dest: "{{ etcd.etcd_workingdir }}/bin/{{ item }}"
    mode: '0755'
  with_items:
    - etcd
    - etcdctl
- name: copy cert file
  copy:
    src: roles/cert/output/{{ item }}
    dest: "{{ etcd.etcd_workingdir }}/cert/{{ item }}"
  with_items:
    - "{{ etcd.rolename }}.pem"
    - "{{ etcd.rolename }}-key.pem"
    - ca.pem
- name: generate etcd service
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service

- include_tasks: ensurerunning.yml
  vars:
    servicename: "{{ etcd.servicename }}"
