#- name: register ENCRYPTION_KEY
#  shell: head -c 32 /dev/urandom | base64
#  register: ENCRYPTION_KEY
#  ignore_errors: true 
#- name: generate encryption-config.yaml
#  template:
#    src: ../templates/encryption-config.yaml.j2
#    dest: /opt/k8s/cfg/encryption-config.yaml
- name: copy audit-policy file
  copy:
    src: ../files/audit-policy.yaml
    dest: /opt/k8s/cfg/audit-policy.yaml
- name: copy proxy-client cert file
  copy:
    src: roles/cert/output/{{ item }}
    dest: /opt/k8s/cert/{{ item }}
  with_items:
    - proxy-client.pem
    - proxy-client-key.pem
- name: copy token file
  copy:
    src: ../files/token.csv
    dest: /opt/k8s/cfg/token.csv
- include_tasks: roles/master/tasks/mastercommon.yml
