- name: copy install file
  copy:
    src: ../files/{{ item }}
    dest: /opt/k8s/bin
  with_items:
    - coredns.yaml.sed
    - deploy.sh
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: install jq
  yum:
    name: jq
    state: present
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: deploy coredns
  shell: |
    chmod +x deploy.sh
    ./deploy.sh -i "{{ service_cidr_prefix }}2"  -d "{{ cluster_dns_domain }}" | kubectl apply -f - 
  args:
    chdir: /opt/k8s/bin
  run_once: true 
  delegate_to: "{{ groups['masters'][0] }}"
