- name: make {{ rolename }} data directory
  file:
    path: /opt/k8s/data/{{ rolename }}
    state: directory

- name: copy {{ rolename }} bin file
  copy:
    src: ../files/{{ rolename }}
    dest: /opt/k8s/bin/{{ rolename }}
    mode: '0755'

- name: copy {{ rolename }} cert file
  copy:
    src: roles/cert/output/{{ item }}
    dest: /opt/k8s/cert/{{ item }}
  with_items:
    - "{{ rolename }}.pem"
    - "{{ rolename }}-key.pem"
- include_tasks: roles/master/tasks/kubeconfig.yml
  when: (rolename   == "kube-controller-manager") or (rolename   == "kube-scheduler") 

- name: generate kube-scheduler config
  template:
    src: roles/kube-scheduler/templates/kube-scheduler.yaml.j2
    dest: /opt/k8s/cfg/kube-scheduler.yaml
  when:  rolename  == "kube-scheduler"
#- name: delete {{ servicename }} service file
#  file:
#    path: /etc/systemd/system/{{ servicename }}.service
#    state: absent
- name: generate {{ servicename }} service file
  template:
    src: ../../{{ rolename }}/templates/{{ servicename }}.service.j2
    dest: /etc/systemd/system/{{ servicename }}.service
    force: yes
  #changed_when: true
  #notify:
  #  - restart service
#- name: restart {{ servicename }} service
#  include_tasks: restartservice.yml
- include_tasks: ensurerunning.yml
