- name: copy metrics and coredns images
  copy: 
    src: "../files/{{ item }}"
    dest: "/opt/{{ item }}"
  with_items:
    #- coredns:1.8.4.tar
    #- metric-server:0.5.0.tar
    - nfs-subdir-external-provisioner.tar
    - registry.tar

- name: load metrics and coredns images
  shell: docker load -i "/opt/{{ item }}"
  with_items:
    #- coredns:1.8.4.tar
    #- metric-server:0.5.0.tar
    - nfs-subdir-external-provisioner.tar 
    - registry.tar
